### ISSUE TITLE
Transmission power?

### ISSUE THREAD

**Issue by ChrisYeen** [SheffieldMLtracking/BLETrack#4]
Can the power of transmission be configured via the CONFIG_BT_CTLR_TX_PWR_ANTENNA attribute in Transmitter/prj.conf to be higher than the default but within the viable range for the [RF amp](https://www.ebay.co.uk/itm/394782255776?mkevt=1&mkpid=0&emsid=e11050.m43.l1123&mkcid=7&ch=osgood&euid=d541b1dd0cbc4e4bbd2ea76060c029a0&bu=44741448833&osub=-1~1&crd=20231218030503&segname=11050) (and will not cause saturation?).

**Comment by ChrisYeen** [comment]
BT840 transmission power information: https://www.fanstel.com/bt840

8dBm max? Probably too high for the RF amp.

**Comment by lionfish0** [comment]
Aren't we using the [BT832XE](https://www.fanstel.com/s/BT832X-p-Product-Specifications.pdf)? which has a 20dBm power output:

![image](https://github.com/SheffieldMLtracking/BLETrack/assets/7914304/d6c4c2da-fe94-400a-8c43-9e0173caad2a)

as you say, this will be too high, as the RF amplifier doesn't want more that, I think, 3dBm as input (to avoid saturation). This also means we should look again at which bluetooth module we should use (I think I chose the BT832XE because of its high power output, that we don't need any more, as we have the 30dB RF amplifier).
